const getAuthUrls = require('./getAuthUrls')
const express = require('express')
const app = express()
console.log(getAuthUrls('github'))
app.get('/', (req, resp) => {resp.sendFile('index.html', {root: '.'})})
app.listen(5210)