let client_id = {}
let client_secret = {}
let scopes = {}
let redirect_uris = {}
let response_types = {}


function setCredentials(cred){
  client_id.amazon = cred.client_secret.client_id.amazon
  client_id.aol = cred.client_secret.client_id.aol
  client_id.autodesk = cred.client_secret.client_id.autodesk
  client_id.apple = cred.client_secret.client_id.apple
  client_id.dailymotion = cred.client_secret.client_id.dailymotion
  client_id.discord = cred.client_secret.client_id.discord
  client_id.dropbox = cred.client_secret.client_id.dropbox
  client_id.evernote = cred.client_secret.client_id.evernote
  client_id.fitbit = cred.client_secret.client_id.fitbit
  client_id.flickr = cred.client_secret.client_id.flickr
  client_id.formstack = cred.client_secret.client_id.formstack
  client_id.github = cred.client_secret.client_id.github
  client_id.gitlab = cred.client_secret.client_id.gitlab
  client_id.goodreads = cred.client_secret.client_id.goodreads
  client_id.google = cred.client_secret.client_id.google
  client_id.instagram = cred.client_secret.client_id.instagram
  client_id.linkedin = cred.client_secret.client_id.linkedin
  client_id.microsoft = cred.client_secret.client_id.microsoft
  client_id.okta = cred.client_secret.client_id.okta
  client_id.paypal = cred.client_secret.client_id.paypal
  client_id.reddit = cred.client_secret.client_id.reddit
  client_id.spotify = cred.client_secret.client_id.spotify
  client_id.stackExchange = cred.client_secret.client_id.stackExchange
  client_id.tumblr = cred.client_secret.client_id.tumblr
  client_id.twitch = cred.client_secret.client_id.twitch
  client_id.twitter = cred.client_secret.client_id.twitter
  client_id.ubuntuOne = cred.client_secret.client_id.ubuntuOne
  client_id.vimeo = cred.client_secret.client_id.vimeo
  client_id.weChat = cred.client_secret.client_id.weChat
  client_id.wordPress = cred.client_secret.client_id.wordPress
  client_id.yahoo = cred.client_secret.client_id.yahoo
  client_id.zsat = cred.client_secret.client_id.zsat

  client_secret.amazon = cred.client_secret.amazon
  client_secret.aol = cred.client_secret.aol
  client_secret.autodesk = cred.client_secret.autodesk
  client_secret.apple = cred.client_secret.apple
  client_secret.dailymotion = cred.client_secret.dailymotion
  client_secret.discord = cred.client_secret.discord
  client_secret.dropbox = cred.client_secret.dropbox
  client_secret.evernote = cred.client_secret.evernote
  client_secret.fitbit = cred.client_secret.fitbit
  client_secret.flickr = cred.client_secret.flickr
  client_secret.formstack = cred.client_secret.formstack
  client_secret.github = cred.client_secret.github
  client_secret.gitlab = cred.client_secret.gitlab
  client_secret.goodreads = cred.client_secret.goodreads
  client_secret.google = cred.client_secret.google
  client_secret.instagram = cred.client_secret.instagram
  client_secret.linkedin = cred.client_secret.linkedin
  client_secret.microsoft = cred.client_secret.microsoft
  client_secret.okta = cred.client_secret.okta
  client_secret.paypal = cred.client_secret.paypal
  client_secret.reddit = cred.client_secret.reddit
  client_secret.spotify = cred.client_secret.spotify
  client_secret.stackExchange = cred.client_secret.stackExchange
  client_secret.tumblr = cred.client_secret.tumblr
  client_secret.twitch = cred.client_secret.twitch
  client_secret.twitter = cred.client_secret.twitter
  client_secret.ubuntuOne = cred.client_secret.ubuntuOne
  client_secret.vimeo = cred.client_secret.vimeo
  client_secret.weChat = cred.client_secret.weChat
  client_secret.wordPress = cred.client_secret.wordPress
  client_secret.yahoo = cred.client_secret.yahoo
  client_secret.zsat = cred.client_secret.zsat

  scopes.amazon = cred.scopes.amazon
  scopes.aol = cred.scopes.aol
  scopes.autodesk = cred.scopes.autodesk
  scopes.apple = cred.scopes.apple
  scopes.dailymotion = cred.scopes.dailymotion
  scopes.discord = cred.scopes.discord
  scopes.dropbox = cred.scopes.dropbox
  scopes.evernote = cred.scopes.evernote
  scopes.fitbit = cred.scopes.fitbit
  scopes.flickr = cred.scopes.flickr
  scopes.formstack = cred.scopes.formstack
  scopes.github = cred.scopes.github
  scopes.gitlab = cred.scopes.gitlab
  scopes.goodreads = cred.scopes.goodreads
  scopes.google = cred.scopes.google
  scopes.instagram = cred.scopes.instagram
  scopes.linkedin = cred.scopes.linkedin
  scopes.microsoft = cred.scopes.microsoft
  scopes.okta = cred.scopes.okta
  scopes.paypal = cred.scopes.paypal
  scopes.reddit = cred.scopes.reddit
  scopes.spotify = cred.scopes.spotify
  scopes.stackExchange = cred.scopes.stackExchange
  scopes.tumblr = cred.scopes.tumblr
  scopes.twitch = cred.scopes.twitch
  scopes.twitter = cred.scopes.twitter
  scopes.ubuntuOne = cred.scopes.ubuntuOne
  scopes.vimeo = cred.scopes.vimeo
  scopes.weChat = cred.scopes.weChat
  scopes.wordPress = cred.scopes.wordPress
  scopes.yahoo = cred.scopes.yahoo
  scopes.zsat = cred.scopes.zsat

  redirect_uris.amazon = cred.redirect_uris.amazon
  redirect_uris.aol = cred.redirect_uris.aol
  redirect_uris.autodesk = cred.redirect_uris.autodesk
  redirect_uris.apple = cred.redirect_uris.apple
  redirect_uris.dailymotion = cred.redirect_uris.dailymotion
  redirect_uris.discord = cred.redirect_uris.discord
  redirect_uris.dropbox = cred.redirect_uris.dropbox
  redirect_uris.evernote = cred.redirect_uris.evernote
  redirect_uris.fitbit = cred.redirect_uris.fitbit
  redirect_uris.flickr = cred.redirect_uris.flickr
  redirect_uris.formstack = cred.redirect_uris.formstack
  redirect_uris.github = cred.redirect_uris.github
  redirect_uris.gitlab = cred.redirect_uris.gitlab
  redirect_uris.goodreads = cred.redirect_uris.goodreads
  redirect_uris.google = cred.redirect_uris.google
  redirect_uris.instagram = cred.redirect_uris.instagram
  redirect_uris.linkedin = cred.redirect_uris.linkedin
  redirect_uris.microsoft = cred.redirect_uris.microsoft
  redirect_uris.okta = cred.redirect_uris.okta
  redirect_uris.paypal = cred.redirect_uris.paypal
  redirect_uris.reddit = cred.redirect_uris.reddit
  redirect_uris.spotify = cred.redirect_uris.spotify
  redirect_uris.stackExchange = cred.redirect_uris.stackExchange
  redirect_uris.tumblr = cred.redirect_uris.tumblr
  redirect_uris.twitch = cred.redirect_uris.twitch
  redirect_uris.twitter = cred.redirect_uris.twitter
  redirect_uris.ubuntuOne = cred.redirect_uris.ubuntuOne
  redirect_uris.vimeo = cred.redirect_uris.vimeo
  redirect_uris.weChat = cred.redirect_uris.weChat
  redirect_uris.wordPress = cred.redirect_uris.wordPress
  redirect_uris.yahoo = cred.redirect_uris.yahoo
  redirect_uris.zsat = cred.redirect_uris.zsat

  response_types.amazon = cred.response_types.amazon
  response_types.aol = cred.response_types.aol
  response_types.autodesk = cred.response_types.autodesk
  response_types.apple = cred.response_types.apple
  response_types.dailymotion = cred.response_types.dailymotion
  response_types.discord = cred.response_types.discord
  response_types.dropbox = cred.response_types.dropbox
  response_types.evernote = cred.response_types.evernote
  response_types.fitbit = cred.response_types.fitbit
  response_types.flickr = cred.response_types.flickr
  response_types.formstack = cred.response_types.formstack
  response_types.github = cred.response_types.github
  response_types.gitlab = cred.response_types.gitlab
  response_types.goodreads = cred.response_types.goodreads
  response_types.google = cred.response_types.google
  response_types.instagram = cred.response_types.instagram
  response_types.linkedin = cred.response_types.linkedin
  response_types.microsoft = cred.response_types.microsoft
  response_types.okta = cred.response_types.okta
  response_types.paypal = cred.response_types.paypal
  response_types.reddit = cred.response_types.reddit
  response_types.spotify = cred.response_types.spotify
  response_types.stackExchange = cred.response_types.stackExchange
  response_types.tumblr = cred.response_types.tumblr
  response_types.twitch = cred.response_types.twitch
  response_types.twitter = cred.response_types.twitter
  response_types.ubuntuOne = cred.response_types.ubuntuOne
  response_types.vimeo = cred.response_types.vimeo
  response_types.weChat = cred.response_types.weChat
  response_types.wordPress = cred.response_types.wordPress
  response_types.yahoo = cred.response_types.yahoo
  response_types.zsat = cred.response_types.zsat
}



module.exports = client_id, client_secret, scopes, redirect_uris, response_types, setCredentials